require 'spec_helper'

describe "the record page" do
  before(:all) do
    stub_request(:get, "http://cataloging-worldcatbib-qa.ent.oclc.org/bib/data/883876185?classificationScheme=LibraryOfCongress").
        to_return(:status => 200, :body => body_content("ocn883876185.atomxml"))
    
    @access_token = OCLC::Auth::AccessToken.new('grant_type', ['FauxService'], 128807, 128807)
    @access_token.value = 'tk_faux_token'
    @access_token.expires_at = DateTime.parse("9999-01-01 00:00:00Z")
  end
  
  context "when displaying a record" do
    before(:all) do
      get '/record/883876185', params={}, rack_env={ 'rack.session' => {:token => @access_token} }
      @doc = Nokogiri::HTML(last_response.body)
      @form_element = @doc.xpath("//form[@id='record-form']").first
    end

    it "should display a form" do
      expect(@form_element).not_to be_nil
    end
    
    it "should have a hidden input field containing the OCLC number" do
      input = @form_element.xpath(".//input[@name='oclc_number'][@type='hidden']").first
      expect(input.attr('value')).to eq('883876185')
    end
    
    it "should have a title input field with the right value" do
      input = @form_element.xpath(".//input[@name='title']").first
      expect(input.attr('value')).to eq('Testing metadata APIs')
    end

    it "should have a sub-title input field with the right value" do
      input = @form_element.xpath(".//input[@name='subtitle']").first
      expect(input.attr('value')).to eq('A comparative analysis')
    end

    it "should have an author input field with the right value" do
      input = @form_element.xpath(".//input[@name='author']").first
      expect(input.attr('value')).to eq('Meyer, Stephen')
    end

    it "should have a publisher input field with the right value" do
      input = @form_element.xpath(".//input[@name='publisher']").first
      expect(input.attr('value')).to eq('OCLC Press')
    end

    it "should have an extent input field with the right value" do
      input = @form_element.xpath(".//input[@name='extent']").first
      expect(input.attr('value')).to eq('190 p.')
    end

    it "should have a subject input field with the right value" do
      input = @form_element.xpath(".//input[@name='subject']").first
      expect(input.attr('value')).to eq('Application Programming Interfaces (APIs)')
    end
    
    it "should display the MARC record" do
      marc_str = "LEADER 00000cam a22000003u 4500\n" + 
          "001 ocn883876185\n" + 
          "003 OCoLC\n" + 
          "005 20140814153938.4\n" + 
          "008 140813s2014    xx            000 u eng d\n" + 
          "040    $a OCPSB $c OCPSB \n" + 
          "035    $a (OCoLC)883876185 \n" + 
          "049    $a MAIN \n" + 
          "100 0  $a Meyer, Stephen \n" + 
          "245 10 $a Testing metadata APIs $b A comparative analysis \n" + 
          "260    $b OCLC Press \n" + 
          "300    $a 190 p. \n" + 
          "500    $a Initial metadata generated by the OCLC Low Barrier Metadata Creation (OCLCLBMC) application. \n" + 
          "650 14 $a Application Programming Interfaces (APIs)"
      marc_pre_element = @doc.xpath("//pre[@id='marc-view']").first
      expect(marc_pre_element.text).to eq(marc_str)
    end
  end
  
  context "when submitting an update to change the author name" do
    before(:all) do
      stub_request(:put, "http://cataloging-worldcatbib-qa.ent.oclc.org/bib/data?classificationScheme=LibraryOfCongress").
          to_return(:status => 201, :body => body_content("ocn883876185-updated.atomxml"))
      stub_request(:get, "http://cataloging-worldcatbib-qa.ent.oclc.org/bib/data/883876185?classificationScheme=LibraryOfCongress").
          to_return(:status => 200, :body => body_content("ocn883876185-updated.atomxml"))

      p = { 
            :oclc_number => '883876185',
            :title => 'Testing metadata APIs',
            :subtitle => 'A comparative analysis',
            :author => 'Meyer, Steve',
            :publisher => 'OCLC Press',
            :extent => '190 p.',
            :subject => 'Application Programming Interfaces (APIs)'
          }
      post( '/update', params=p, rack_env={ 'rack.session' => {:token => @access_token} } )
    end
    
    it "should respond with a redirect back to the record display page" do
      expect(last_response.redirect?)
      expect(last_response.header['Location']).to eq("http://example.org/record/883876185")
    end
  end
  
  context "when submitting a new record" do
    before(:all) do
      stub_request(:post, "http://cataloging-worldcatbib-qa.ent.oclc.org/bib/data?classificationScheme=LibraryOfCongress").
          to_return(:status => 201, :body => body_content("ocn883876185.atomxml"))
      stub_request(:get, "http://cataloging-worldcatbib-qa.ent.oclc.org/bib/data/883876185?classificationScheme=LibraryOfCongress").
          to_return(:status => 200, :body => body_content("ocn883876185.atomxml"))

      p = { 
            :title => 'Testing metadata APIs',
            :subtitle => 'A comparative analysis',
            :author => 'Meyer, Stephen',
            :publisher => 'OCLC Press',
            :extent => '190 p.',
            :subject => 'Application Programming Interfaces (APIs)'
          }
      post( '/create', params=p, rack_env={ 'rack.session' => {:token => @access_token} } )
    end
    
    it "should respond with a redirect to the record display page" do
      expect(last_response.redirect?)
      expect(last_response.header['Location']).to eq("http://example.org/record/883876185")
    end
  end
end
