module LBMC

  SOURCE_NOTE = 'Initial metadata generated by the OCLC Low Barrier Metadata Creation (OCLCLBMC) application.'
  ATOM_WRAPPED_MARC_MIMETYPE = 'application/atom+xml;content="application/vnd.oclc.marc21+xml"'
  MARC_XML_MIMETYPE = 'application/vnd.oclc.marc21+xml'

end