# encoding: utf-8
af: "Afghanistan"
alu: "Alabama"
aku: "Alaska"
aa: "Albania"
abc: "Alberta"
ae: "Algeria"
as: "American Samoa"
an: "Andorra"
ao: "Angola"
am: "Anguilla"
ay: "Antarctica"
aq: "Antigua and Barbuda"
ag: "Argentina"
azu: "Arizona"
aru: "Arkansas"
ai: "Armenia (Republic)"
aw: "Aruba"
at: "Australia"
aca: "Australian Capital Territory"
au: "Austria"
aj: "Azerbaijan"
bf: "Bahamas"
ba: "Bahrain"
bg: "Bangladesh"
bb: "Barbados"
bw: "Belarus"
be: "Belgium"
bh: "Belize"
dm: "Benin"
bm: "Bermuda Islands"
bt: "Bhutan"
bo: "Bolivia"
bn: "Bosnia and Hercegovina"
bs: "Botswana"
bv: "Bouvet Island"
bl: "Brazil"
bcc: "British Columbia"
bi: "British Indian Ocean Territory"
vb: "British Virgin Islands"
bx: "Brunei"
bu: "Bulgaria"
uv: "Burkina Faso"
br: "Burma"
bd: "Burundi"
cv: "Cabo Verde"
cau: "California"
cb: "Cambodia"
cm: "Cameroon"
xxc: "Canada"
ca: "Caribbean Netherlands"
cj: "Cayman Islands"
cx: "Central African Republic"
cd: "Chad"
cl: "Chile"
cc: "China"
ch: "China (Republic : 1949- )"
xa: "Christmas Island (Indian Ocean)"
xb: "Cocos (Keeling) Islands"
ck: "Colombia"
cou: "Colorado"
cq: "Comoros"
cf: "Congo (Brazzaville)"
cg: "Congo (Democratic Republic)"
ctu: "Connecticut"
cw: "Cook Islands"
xga: "Coral Sea Islands Territory"
cr: "Costa Rica"
iv: "Cote d'Ivoire"
ci: "Croatia"
cu: "Cuba"
co: "Curacao"
cy: "Cyprus"
xr: "Czech Republic"
deu: "Delaware"
dk: "Denmark"
dcu: "District of Columbia"
ft: "Djibouti"
dq: "Dominica"
dr: "Dominican Republic"
ec: "Ecuador"
ua: "Egypt"
es: "El Salvador"
enk: "England"
eg: "Equatorial Guinea"
ea: "Eritrea"
er: "Estonia"
et: "Ethiopia"
fk: "Falkland Islands"
fa: "Faroe Islands"
fj: "Fiji"
fi: "Finland"
flu: "Florida"
fr: "France"
fg: "French Guiana"
fp: "French Polynesia"
go: "Gabon"
gm: "Gambia"
gz: "Gaza Strip"
gau: "Georgia"
gs: "Georgia (Republic)"
gw: "Germany"
gh: "Ghana"
gi: "Gibraltar"
gr: "Greece"
gl: "Greenland"
gd: "Grenada"
gp: "Guadeloupe"
gu: "Guam"
gt: "Guatemala"
gv: "Guinea"
pg: "Guinea-Bissau"
gy: "Guyana"
ht: "Haiti"
hiu: "Hawaii"
hm: "Heard and McDonald Islands"
ho: "Honduras"
hu: "Hungary"
ic: "Iceland"
idu: "Idaho"
ilu: "Illinois"
ii: "India"
inu: "Indiana"
io: "Indonesia"
iau: "Iowa"
ir: "Iran"
iq: "Iraq"
iy: "Iraq-Saudi Arabia Neutral Zone"
ie: "Ireland"
is: "Israel"
it: "Italy"
jm: "Jamaica"
ja: "Japan"
ji: "Johnston Atoll"
jo: "Jordan"
ksu: "Kansas"
kz: "Kazakhstan"
kyu: "Kentucky"
ke: "Kenya"
gb: "Kiribati"
kn: "Korea (North)"
ko: "Korea (South)"
kv: "Kosovo"
ku: "Kuwait"
kg: "Kyrgyzstan"
ls: "Laos"
lv: "Latvia"
le: "Lebanon"
lo: "Lesotho"
lb: "Liberia"
ly: "Libya"
lh: "Liechtenstein"
li: "Lithuania"
lau: "Louisiana"
lu: "Luxembourg"
xn: "Macedonia"
mg: "Madagascar"
meu: "Maine"
mw: "Malawi"
my: "Malaysia"
xc: "Maldives"
ml: "Mali"
mm: "Malta"
mbc: "Manitoba"
xe: "Marshall Islands"
mq: "Martinique"
mdu: "Maryland"
mau: "Massachusetts"
mu: "Mauritania"
mf: "Mauritius"
ot: "Mayotte"
mx: "Mexico"
miu: "Michigan"
fm: "Micronesia (Federated States)"
xf: "Midway Islands"
mnu: "Minnesota"
msu: "Mississippi"
mou: "Missouri"
mv: "Moldova"
mc: "Monaco"
mp: "Mongolia"
mtu: "Montana"
mo: "Montenegro"
mj: "Montserrat"
mr: "Morocco"
mz: "Mozambique"
sx: "Namibia"
nu: "Nauru"
nbu: "Nebraska"
np: "Nepal"
ne: "Netherlands"
nvu: "Nevada"
nkc: "New Brunswick"
nl: "New Caledonia"
nhu: "New Hampshire"
nju: "New Jersey"
nmu: "New Mexico"
xna: "New South Wales"
nyu: "New York (State)"
nz: "New Zealand"
nfc: "Newfoundland and Labrador"
nq: "Nicaragua"
ng: "Niger"
nr: "Nigeria"
xh: "Niue"
nx: "Norfolk Island"
ncu: "North Carolina"
ndu: "North Dakota"
nik: "Northern Ireland"
nw: "Northern Mariana Islands"
xoa: "Northern Territory"
ntc: "Northwest Territories"
"no": "Norway"
nsc: "Nova Scotia"
nuc: "Nunavut"
ohu: "Ohio"
oku: "Oklahoma"
mk: "Oman"
onc: "Ontario"
oru: "Oregon"
pk: "Pakistan"
pw: "Palau"
pn: "Panama"
pp: "Papua New Guinea"
pf: "Paracel Islands"
py: "Paraguay"
pau: "Pennsylvania"
pe: "Peru"
ph: "Philippines"
pc: "Pitcairn Island"
pl: "Poland"
po: "Portugal"
pic: "Prince Edward Island"
pr: "Puerto Rico"
qa: "Qatar"
quc: "Quebec (Province)"
qea: "Queensland"
re: "Reunion"
riu: "Rhode Island"
rm: "Romania"
ru: "Russia (Federation)"
rw: "Rwanda"
xj: "Saint Helena"
xd: "Saint Kitts-Nevis"
xk: "Saint Lucia"
xl: "Saint Pierre and Miquelon"
xm: "Saint Vincent and the Grenadines"
sc: "Saint-Barthelemy"
st: "Saint-Martin"
ws: "Samoa"
sm: "San Marino"
sf: "Sao Tome and Principe"
snc: "Saskatchewan"
su: "Saudi Arabia"
stk: "Scotland"
sg: "Senegal"
rb: "Serbia"
se: "Seychelles"
sl: "Sierra Leone"
si: "Singapore"
sn: "Sint Maarten"
xo: "Slovakia"
xv: "Slovenia"
bp: "Solomon Islands"
so: "Somalia"
sa: "South Africa"
xra: "South Australia"
scu: "South Carolina"
sdu: "South Dakota"
xs: "South Georgia and the South Sandwich Islands"
sd: "South Sudan"
sp: "Spain"
sh: "Spanish North Africa"
xp: "Spratly Island"
ce: "Sri Lanka"
sj: "Sudan"
sr: "Surinam"
sq: "Swaziland"
sw: "Sweden"
sz: "Switzerland"
sy: "Syria"
ta: "Tajikistan"
tz: "Tanzania"
tma: "Tasmania"
tnu: "Tennessee"
fs: "Terres australes et antarctiques francaises"
txu: "Texas"
th: "Thailand"
em: "Timor-Leste"
tg: "Togo"
tl: "Tokelau"
to: "Tonga"
tr: "Trinidad and Tobago"
ti: "Tunisia"
tu: "Turkey"
tk: "Turkmenistan"
tc: "Turks and Caicos Islands"
tv: "Tuvalu"
ug: "Uganda"
un: "Ukraine"
ts: "United Arab Emirates"
xxk: "United Kingdom"
uik: "United Kingdom Misc. Islands"
xxu: "United States"
uc: "United States Misc. Caribbean Islands"
up: "United States Misc. Pacific Islands"
uy: "Uruguay"
utu: "Utah"
uz: "Uzbekistan"
nn: "Vanuatu"
vp: "Various places"
vc: "Vatican City"
ve: "Venezuela"
vtu: "Vermont"
vra: "Victoria"
vm: "Vietnam"
vi: "Virgin Islands of the United States"
vau: "Virginia"
wk: "Wake Island"
wlk: "Wales"
wf: "Wallis and Futuna"
wau: "Washington (State)"
wj: "West Bank of the Jordan River"
wvu: "West Virginia"
wea: "Western Australia"
ss: "Western Sahara"
wiu: "Wisconsin"
wyu: "Wyoming"
ye: "Yemen"
ykc: "Yukon Territory"
za: "Zambia"
rh: "Zimbabwe"