# encoding: utf-8
af: "Afghanistan"
alu: "Alabama"
aku: "Alaska"
aa: "Albania"
abc: "Alberta"
ae: "Algeria"
as: "American Samoa"
an: "Andorra"
ao: "Angola"
am: "Anguilla"
ay: "Antarctica"
aq: "Antigua and Barbuda"
ag: "Argentina"
azu: "Arizona"
aru: "Arkansas"
ai: "Armenia (Republic)"
aw: "Aruba"
at: "Australia"
aca: "Australian Capital Territory"
au: "Austria"
aj: "Azerbaijan"
bf: "Bahamas"
ba: "Bahrain"
bg: "Bangladesh"
bb: "Barbados"
bw: "Belarus"
be: "Belgium"
bh: "Belize"
dm: "Benin"
bm: "Bermuda Islands"
bt: "Bhutan"
bo: "Bolivia"
bn: "Bosnia and Hercegovina"
bs: "Botswana"
bv: "Bouvet Island"
bl: "Brazil"
bcc: "British Columbia"
bi: "British Indian Ocean Territory"
vb: "British Virgin Islands"
bx: "Brunei"
bu: "Bulgaria"
uv: "Burkina Faso"
br: "Burma"
bd: "Burundi"
cv: "Cabo Verde"
cau: "California"
cb: "Cambodia"
cm: "Cameroon"
xxc: "Canada"
ca: "Caribbean Netherlands"
cj: "Cayman Islands"
cx: "Central African Republic"
cd: "Chad"
cl: "Chile"
cc: "China"
ch: "China (Republic : 1949- )"
xa: "Christmas Island (Indian Ocean)"
xb: "Cocos (Keeling) Islands"
ck: "Colombia"
cou: "Colorado"
cq: "Comoros"
cf: "Congo (Brazzaville)"
cg: "Congo (Democratic Republic)"
ctu: "Connecticut"
cw: "Cook Islands"
xga: "Coral Sea Islands Territory"
cr: "Costa Rica"
iv: "Cote d'Ivoire"
ci: "Croatia"
cu: "Cuba"
co: "Curaçao"
cy: "Cyprus"
xr: "Czech Republic"
deu: "Delaware"
dk: "Denmark"
dcu: "District of Columbia"
ft: "Djibouti"
dq: "Dominica"
dr: "Dominican Republic"
ec: "Ecuador"
ua: "Egypt"
es: "El Salvador"
enk: "England"
eg: "Equatorial Guinea"
ea: "Eritrea"
er: "Estonia"
et: "Ethiopia"
fk: "Falkland Islands"
fa: "Faroe Islands"
fj: "Fiji"
fi: "Finland"
flu: "Florida"
fr: "France"
fg: "French Guiana"
fp: "French Polynesia"
go: "Gabon"
gm: "Gambia"
gz: "Gaza Strip"
gau: "Georgia"
gs: "Georgia (Republic)"
gw: "Germany"
gh: "Ghana"
gi: "Gibraltar"
gr: "Greece"
gl: "Greenland"
gd: "Grenada"
gp: "Guadeloupe"
gu: "Guam"
gt: "Guatemala"
gv: "Guinea"
pg: "Guinea-Bissau"
gy: "Guyana"
ht: "Haiti"
hiu: "Hawaii"
hm: "Heard and McDonald Islands"
ho: "Honduras"
hu: "Hungary"
ic: "Iceland"
idu: "Idaho"
ilu: "Illinois"
ii: "India"
inu: "Indiana"
io: "Indonesia"
iau: "Iowa"
ir: "Iran"
iq: "Iraq"
iy: "Iraq-Saudi Arabia Neutral Zone"
ie: "Ireland"
is: "Israel"
it: "Italy"
jm: "Jamaica"
ja: "Japan"
ji: "Johnston Atoll"
jo: "Jordan"
ksu: "Kansas"
kz: "Kazakhstan"
kyu: "Kentucky"
ke: "Kenya"
gb: "Kiribati"
kn: "Korea (North)"
ko: "Korea (South)"
kv: "Kosovo"
ku: "Kuwait"
kg: "Kyrgyzstan"
ls: "Laos"
lv: "Latvia"
le: "Lebanon"
lo: "Lesotho"
lb: "Liberia"
ly: "Libya"
lh: "Liechtenstein"
li: "Lithuania"
lau: "Louisiana"
lu: "Luxembourg"