# encoding: utf-8
af: "Afghanistan"
alu: "Alabama"
aku: "Alaska"
aa: "Albania"
abc: "Alberta"
ae: "Algeria"
as: "American Samoa"
an: "Andorra"
ao: "Angola"
am: "Anguilla"
ay: "Antarctica"
aq: "Antigua and Barbuda"
ag: "Argentina"
azu: "Arizona"
aru: "Arkansas"
ai: "Armenia (Republic)"
aw: "Aruba"
at: "Australia"
aca: "Australian Capital Territory"
au: "Austria"
aj: "Azerbaijan"
bf: "Bahamas"
ba: "Bahrain"
bg: "Bangladesh"
bb: "Barbados"
bw: "Belarus"