abk: "Abkhaz"
ace: "Achinese"
ach: "Acoli"
ada: "Adangme"
ady: "Adygei"
aar: "Afar"
afh: "Afrihili (Artificial language)"
afr: "Afrikaans"
afa: "Afroasiatic (Other)"
aka: "Akan"
akk: "Akkadian"
alb: "Albanian"
ale: "Aleut"
alg: "Algonquian (Other)"
ajm: "Aljamia"
tut: "Altaic (Other)"
amh: "Amharic"
apa: "Apache languages"
ara: "Arabic"
arg: "Aragonese Spanish"
arc: "Aramaic"
arp: "Arapaho"
arw: "Arawak"
arm: "Armenian"
art: "Artificial (Other)"
asm: "Assamese"
ath: "Athapascan (Other)"
aus: "Australian languages"
map: "Austronesian (Other)"
ava: "Avaric"
ave: "Avestan"
awa: "Awadhi"
aym: "Aymara"
aze: "Azerbaijani"
ast: "Bable"
ban: "Balinese"
bat: "Baltic (Other)"
bal: "Baluchi"
bam: "Bambara"
bai: "Bamileke languages"
bad: "Banda"
bnt: "Bantu (Other)"
bas: "Basa"
bak: "Bashkir"
baq: "Basque"
btk: "Batak"
bej: "Beja"
bel: "Belarusian"
bem: "Bemba"
ben: "Bengali"
ber: "Berber (Other)"
bho: "Bhojpuri"
bih: "Bihari"
bik: "Bikol"
bis: "Bislama"
bos: "Bosnian"
bra: "Braj"
bre: "Breton"
bug: "Bugis"
bul: "Bulgarian"
bua: "Buriat"
bur: "Burmese"
cad: "Caddo"
car: "Carib"
cat: "Catalan"
cau: "Caucasian (Other)"
ceb: "Cebuano"
cel: "Celtic (Other)"
cai: "Central American Indian (Other)"
chg: "Chagatai"
cmc: "Chamic languages"
cha: "Chamorro"
che: "Chechen"
chr: "Cherokee"
chy: "Cheyenne"
chb: "Chibcha"
chi: "Chinese"
chn: "Chinook jargon"
chp: "Chipewyan"
cho: "Choctaw"
chu: "Church Slavic"
chv: "Chuvash"
cop: "Coptic"
cor: "Cornish"
cos: "Corsican"
cre: "Cree"
mus: "Creek"
crp: "Creoles and Pidgins (Other)"
cpe: "Creoles and Pidgins, English-based (Other)"
cpf: "Creoles and Pidgins, French-based (Other)"
cpp: "Creoles and Pidgins, Portuguese-based (Other)"
crh: "Crimean Tatar"
scr: "Croatian"
cus: "Cushitic (Other)"
cze: "Czech"
dak: "Dakota"
dan: "Danish"
dar: "Dargwa"
day: "Dayak"
del: "Delaware"
din: "Dinka"
div: "Divehi"
doi: "Dogri"
dgr: "Dogrib"
dra: "Dravidian (Other)"
dua: "Duala"
dut: "Dutch"
dum: "Dutch, Middle (ca. 1050-1350)"
dyu: "Dyula"
dzo: "Dzongkha"
bin: "Edo"
efi: "Efik"
egy: "Egyptian"
eka: "Ekajuk"
elx: "Elamite"
eng: "English"
enm: "English, Middle (1100-1500)"
ang: "English, Old (ca. 450-1100)"
esk: "Eskimo languages"
epo: "Esperanto"
esp: "Esperanto"
est: "Estonian"
eth: "Ethiopic"
gez: "Ethiopic"
ewe: "Ewe"
ewo: "Ewondo"
fan: "Fang"
fat: "Fanti"
fao: "Faroese"
far: "Faroese"
fij: "Fijian"
fin: "Finnish"
fiu: "Finno-Ugrian (Other)"
fon: "Fon"
fre: "French"
frm: "French, Middle (ca. 1400-1600)"
fro: "French, Old (ca. 842-1400)"
fri: "Frisian"
fry: "Frisian"
fur: "Friulian"
ful: "Fula"
gaa: "Ga"
gag: "Galician"
glg: "Galician"
lug: "Ganda"
gay: "Gayo"
gba: "Gbaya"
geo: "Georgian"
ger: "German"
gmh: "German, Middle High (ca. 1050-1500)"
goh: "German, Old High (ca. 750-1050)"
gem: "Germanic (Other)"
gil: "Gilbertese"
gon: "Gondi"
gor: "Gorontalo"
got: "Gothic"
grb: "Grebo"
grc: "Greek, Ancient (to 1453)"
gre: "Greek, Modern (1453- )"
grn: "Guarani"
gua: "Guarani"
guj: "Gujarati"
gwi: "Gwich'in"
hai: "Haida"
hat: "Haitian French Creole"
hau: "Hausa"
haw: "Hawaiian"
heb: "Hebrew"
her: "Herero"
hil: "Hiligaynon"
him: "Himachali"
hin: "Hindi"
hmo: "Hiri Motu"
hit: "Hittite"
hmn: "Hmong"
hun: "Hungarian"
hup: "Hupa"
iba: "Iban"
ice: "Icelandic"
ido: "Ido"
ibo: "Igbo"
ijo: "Ijo"
ilo: "Iloko"
smn: "Inari Sami"
inc: "Indic (Other)"
ine: "Indo-European (Other)"
ind: "Indonesian"
inh: "Ingush"
ina: "Interlingua (International Auxiliary Language Association)"
int: "Interlingua (International Auxiliary Language Association)"
ile: "Interlingue"
iku: "Inuktitut"
ipk: "Inupiaq"
ira: "Iranian (Other)"
gle: "Irish"
iri: "Irish"
mga: "Irish, Middle (ca. 1100-1550)"
sga: "Irish, Old (to 1100)"
iro: "Iroquoian (Other)"
ita: "Italian"
jpn: "Japanese"
jav: "Javanese"
jrb: "Judeo-Arabic"
jpr: "Judeo-Persian"
kbd: "Kabardian"
kab: "Kabyle"
kac: "Kachin"
kal: "Kalatdlisut"
xal: "Kalmyk"
kam: "Kamba"
kan: "Kannada"
kau: "Kanuri"
kaa: "Kara-Kalpak"
kar: "Karen"
kas: "Kashmiri"
kaw: "Kawi"
kaz: "Kazakh"
kha: "Khasi"
cam: "Khmer"
khm: "Khmer"
khi: "Khoisan (Other)"
kho: "Khotanese"
kik: "Kikuyu"
kmb: "Kimbundu"
kin: "Kinyarwanda"
kom: "Komi"
kon: "Kongo"
kok: "Konkani"
kor: "Korean"
kpe: "Kpelle"
kro: "Kru"
kua: "Kuanyama"
kum: "Kumyk"
kur: "Kurdish"
kru: "Kurukh"
kos: "Kusaie"
kus: "Kusaie"
kut: "Kutenai"
kir: "Kyrgyz"
lad: "Ladino"
lah: "Lahnda"
lam: "Lamba"
lao: "Lao"
lat: "Latin"
lav: "Latvian"
ltz: "Letzeburgesch"
lez: "Lezgian"
lim: "Limburgish"
lin: "Lingala"
lit: "Lithuanian"
nds: "Low German"
loz: "Lozi"
lub: "Luba-Katanga"
lua: "Luba-Lulua"
lui: "Luiseno"
smj: "Lule Sami"
lun: "Lunda"
luo: "Luo (Kenya and Tanzania)"
lus: "Lushai"
mac: "Macedonian"
mad: "Madurese"
mag: "Magahi"
mai: "Maithili"
mak: "Makasar"
mla: "Malagasy"
mlg: "Malagasy"
may: "Malay"
mal: "Malayalam"
mlt: "Maltese"
mnc: "Manchu"
mdr: "Mandar"
man: "Mandingo"
mni: "Manipuri"
mno: "Manobo languages"
glv: "Manx"
max: "Manx"
mao: "Maori"
arn: "Mapuche"
mar: "Marathi"
chm: "Mari"
mah: "Marshallese"
mwr: "Marwari"
mas: "Masai"
myn: "Mayan languages"
men: "Mende"
mic: "Micmac"
min: "Minangkabau"
mis: "Miscellaneous languages"
moh: "Mohawk"
mol: "Moldavian"
mon: "Mongolian"
lol: "Mongo-Nkundu"
mkh: "Mon-Khmer (Other)"
mos: "Moore"
mul: "Multiple languages"
mun: "Munda (Other)"
nah: "Nahuatl"
nau: "Nauru"
nav: "Navajo"
nbl: "Ndebele (South Africa)"
nde: "Ndebele (Zimbabwe)"
ndo: "Ndonga"
nap: "Neapolitan Italian"
nep: "Nepali"
new: "Newari"
nia: "Nias"
nic: "Niger-Kordofanian (Other)"
ssa: "Nilo-Saharan (Other)"
niu: "Niuean"
zxx: "No Linguistic Content"
nog: "Nogai"
nai: "North American Indian (Other)"
sme: "Northern Sami"
nso: "Northern Sotho"
nob: "Norwegian (Bokmal)"
nno: "Norwegian (Nynorsk)"
nor: "Norwegian"
nub: "Nubian languages"
nym: "Nyamwezi"
nya: "Nyanja"
nyn: "Nyankole"
nyo: "Nyoro"
nzi: "Nzima"
lan: "Occitan (post-1500)"
oci: "Occitan (post-1500)"
oji: "Ojibwa"
non: "Old Norse"
peo: "Old Persian (ca. 600-400 B.C.)"
ori: "Oriya"
gal: "Oromo"
orm: "Oromo"
osa: "Osage"
oss: "Ossetic"
oto: "Otomian languages"
pal: "Pahlavi"
pau: "Palauan"
pli: "Pali"
pam: "Pampanga"
pag: "Pangasinan"
pan: "Panjabi"
pap: "Papiamento"
paa: "Papuan (Other)"
per: "Persian"
phi: "Philippine (Other)"
phn: "Phoenician"
pol: "Polish"
pon: "Ponape"
por: "Portuguese"
pra: "Prakrit languages"
pro: "Provencal (to 1500)"
pus: "Pushto"
que: "Quechua"
roh: "Raeto-Romance"
raj: "Rajasthani"
rap: "Rapanui"
rar: "Rarotongan"
roa: "Romance (Other)"
rom: "Romani"
rum: "Romanian"
run: "Rundi"
rus: "Russian"
sal: "Salishan languages"
sam: "Samaritan Aramaic"
lap: "Sami"
smi: "Sami"
sao: "Samoan"
smo: "Samoan"
sad: "Sandawe"
sag: "Sango (Ubangi Creole)"
san: "Sanskrit"
sat: "Santali"
srd: "Sardinian"
sas: "Sasak"
sco: "Scots"
gae: "Scottish Gaelic"
gla: "Scottish Gaelic"
sel: "Selkup"
sem: "Semitic (Other)"
scc: "Serbian"
srr: "Serer"
shn: "Shan"
sho: "Shona"
sna: "Shona"
iii: "Sichuan Yi"
sid: "Sidamo"
sgn: "Sign languages"
bla: "Siksika"
snd: "Sindhi"
sin: "Sinhalese"
snh: "Sinhalese"
sit: "Sino-Tibetan (Other)"
sio: "Siouan (Other)"
sms: "Skolt Sami"
den: "Slave"
sla: "Slavic (Other)"
slo: "Slovak"
slv: "Slovenian"
sog: "Sogdian"
som: "Somali"
son: "Songhai"
snk: "Soninke"
wen: "Sorbian languages"
sot: "Sotho"
sso: "Sotho"
sai: "South American Indian (Other)"
sma: "Southern Sami"
spa: "Spanish"
suk: "Sukuma"
sux: "Sumerian"
sun: "Sundanese"
sus: "Susu"
swa: "Swahili"
ssw: "Swazi"
swz: "Swazi"
swe: "Swedish"
syr: "Syriac"
tag: "Tagalog"
tgl: "Tagalog"
tah: "Tahitian"
tai: "Tai (Other)"
taj: "Tajik"
tgk: "Tajik"
tmh: "Tamashek"
tam: "Tamil"
tar: "Tatar"
tat: "Tatar"
tel: "Telugu"
tem: "Temne"
ter: "Terena"
tet: "Tetum"
tha: "Thai"
tib: "Tibetan"
tig: "Tigre"
tir: "Tigrinya"
tiv: "Tiv"
tli: "Tlingit"
tpi: "Tok Pisin"
tkl: "Tokelauan"
tog: "Tonga (Nyasa)"
ton: "Tongan"
chk: "Truk"
tru: "Truk"
tsi: "Tsimshian"
tso: "Tsonga"
tsn: "Tswana"
tsw: "Tswana"
tum: "Tumbuka"
tup: "Tupi languages"
tur: "Turkish"
ota: "Turkish, Ottoman"
tuk: "Turkmen"
tvl: "Tuvaluan"
tyv: "Tuvinian"
twi: "Twi"
udm: "Udmurt"
uga: "Ugaritic"
uig: "Uighur"
ukr: "Ukrainian"
umb: "Umbundu"
urd: "Urdu"
uzb: "Uzbek"
vai: "Vai"
ven: "Venda"
vie: "Vietnamese"
vol: "Volapuk"
vot: "Votic"
wak: "Wakashan languages"
wal: "Walamo"
wln: "Walloon"
war: "Waray"
was: "Washo"
wel: "Welsh"
wol: "Wolof"
xho: "Xhosa"
sah: "Yakut"
yao: "Yao (Africa)"
yap: "Yapese"
yid: "Yiddish"
yor: "Yoruba"
ypk: "Yupik languages"
znd: "Zande"
zap: "Zapotec"
zen: "Zenaga"
zha: "Zhuang"
zul: "Zulu"
zun: "Zuni"